### ISSUE TITLE
pubkey.txt becomes empty after firmware update

### ISSUE THREAD

**Issue by oroant** [MicrochipTech/AVR-IoT-WG-Sensor-Node#5] opened 2019-01-25 14:38 UTC
Just upgraded the board with 1.0.2. The content of PUBKEY.TXT can not be retrieved anymore. 
The txt files now shows: 
```
--------------------------------------------
Unknown command. List of available commands:
reset
device
key
reconnect
version
cli_version
wifi <ssid>[,<pass>,[authType]]
debug
--------------------------------------------
```

**Comment by luciodj** [comment] 2019-01-26 15:28
Thanks for reporting it! We could indeed reproduce it. 
The problem is easily resolved by power cycling (disconnecting the board and re-connecting it) to force the DEBUG chip to refresh its cached pubkey.txt information. 
We will be seeking a fix in upcoming sw revs.
Many thanks!

**Closed as completed by luciodj** 2019-01-26 15:28 UTC
